### ISSUE TITLE
Login-as-guest Lambda function returns "Internal server error"

### ISSUE THREAD

**Issue by hjp309** [aws-solutions-library-samples/guidance-for-custom-game-backend-hosting-on-aws#15] opened 2023-10-13 23:34 UTC
After deploying the stack and testing the _login-as-guest_ endpoint, I get returned a 502 "Internal server error".

Here is the error message:
`Fri Oct 13 23:25:42 UTC 2023 : Endpoint response body before transformations: {"errorMessage": "Expecting value: line 1 column 1 (char 0)", "errorType": "JSONDecodeError", "requestId": "fcf74ad2-a25a-4fcf-a422-eb7290dc5a9c", "stackTrace": ["  File \"/var/task/aws_lambda_powertools/tracing/tracer.py\", line 313, in decorate\n    response = lambda_handler(event, context, **kwargs)\n", "  File \"/var/task/login_as_guest.py\", line 120, in lambda_handler\n    auth_token, refresh_token, auth_token_expires_in, refresh_token_expires_in = encrypt(payload, \"guest\")\n", "  File \"/var/task/encryption_and_decryption.py\", line 85, in encrypt\n    auth_token, auth_token_expires_in = encrypt_payload(payload, private_key, scope, \"gamebackend\", access_token_expiration, scope)\n", "  File \"/var/task/encryption_and_decryption.py\", line 105, in encrypt_payload\n    key_dict = json.loads(private_key)\n", "  File \"/var/lang/lib/python3.11/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n", "  File \"/var/lang/lib/python3.1 [TRUNCATED]
Fri Oct 13 23:25:42 UTC 2023 : Lambda execution failed with status 200 due to customer function error: Expecting value: line 1 column 1 (char 0). Lambda request id: fcf74ad2-a25a-4fcf-a422-eb7290dc5a9c
Fri Oct 13 23:25:42 UTC 2023 : Method completed with status: 502`

Google Play and Apple Login API calls all seem to work and return the correct status codes, but login-as-guest does not.

I have deployed the exact same stack on a different Unity project and it works as intended. 

Could this relate to a permissions / policy issue?

**Comment by juhoaws** [comment] 2023-10-14 01:21
Hi!

It looks like the login-as-guest function build process has probably failed for some reason and you don't have anything in the code file. You could try deleting all the `.asset` folders under `CustomIdentityComponent/cdk.out/`. This way when you redeploy it should rebuild the package. 

Let me know if that helps and let's try to see if we can find a way to reproduce this, haven't seen it before!

**Comment by hjp309** [comment] 2023-10-14 11:39
I was able to resolve the issue after referencing a similar issue [here](https://github.com/aws/aws-sam-cli/issues/5799) 

I ran  `npm -g install aws-cdk`, redeployed and it started working again. I actually updated the cdk after being prompted of the new version before I started getting this error, so maybe there's a mismatch?

**Comment by juhoaws** [comment] 2023-10-16 15:51
Ok, so it might be that the Lambda packaging doesn't work correctly with older CDK versions. I'll keep an eye on this and see if we can reproduce anything but will close the issue for now

**Closed by juhoaws** 2023-10-16 15:51 UTC
